apiVersion: v1
kind: Service
metadata:
  name: smartfarm-app
  labels:
    app: smartfarm-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: smartfarm-app
  type: LoadBalancer