"""Initial migration

Revision ID: 58e5f2f237de
Revises: 21974de1b56f
Create Date: 2025-04-15 14:10:45.900850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e5f2f237de'
down_revision: Union[str, None] = '21974de1b56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_us_id', table_name='contact_us')
    op.drop_table('contact_us')
    op.drop_index('ix_password_reset_otp_email', table_name='password_reset_otp')
    op.drop_index('ix_password_reset_otp_id', table_name='password_reset_otp')
    op.drop_table('password_reset_otp')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('user_type', sa.VARCHAR(length=6), nullable=False),
    sa.Column('contact_number', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('password_reset_otp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('otp', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_reset_otp_id', 'password_reset_otp', ['id'], unique=False)
    op.create_index('ix_password_reset_otp_email', 'password_reset_otp', ['email'], unique=False)
    op.create_table('contact_us',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), nullable=False),
    sa.Column('farm_size', sa.VARCHAR(), nullable=True),
    sa.Column('primary_waste_type', sa.VARCHAR(), nullable=True),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_us_id', 'contact_us', ['id'], unique=False)
    # ### end Alembic commands ###
